[build]
  environment = { CI = "false" }

[[redirects]]
from = '/admin'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-main'
status = 200
force = true

[[redirects]]
from = '/users'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-recipe/admin'
status = 200
force = true

[[redirects]]
from = '/reports'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-recipe/admin'
status = 200
force = true

[[redirects]]
from = '/recipes'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-recipe/admin'
status = 200
force = true

[[redirects]]
from = '/presigned-url'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev'
status = 200
force = true