[build]
  environment = { CI = "false" }

[[redirects]]
from = '/main_proxy/*'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-main/:splat'
status = 200
force = true

[[redirects]]
from = '/recipe_proxy/*'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/dev-ice-bulter-recipe/admin/:splat'
status = 200
force = true

[[redirects]]
from = '/presigned-url/*'
to = 'https://za8hqdiis4.execute-api.ap-northeast-2.amazonaws.com/dev/:splat'
status = 200
force = true