[build]
  environment = { CI = "false" }
  command = "npm run build"
  publish = "build"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"

[[redirects]]
from = '/main_proxy/*'
to = "env(GATEWAY)/dev/dev-ice-bulter-main/:splat"
status = 200
force = true

[[redirects]]
from = '/recipe_proxy/*'
to = "env(GATEWAY)/dev/dev-ice-bulter-recipe/admin/:splat"
status = 200
force = true

[[redirects]]
from = '/s3_proxy/*'
to = "env(GATEWAY)/dev/:splat"
status = 200
force = true

[[redirects]]
from = '/s3_direct_proxy/*'
to = "env(S3)/dev/:splat"
status = 200
force = true